## 4-е домашнее задание - Библиотека numpy Урзов Александр Николаевич


Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  
Урзов Александр Николаевич НПМбд-02-20
Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [2]:
import numpy as np


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [3]:
arr2 = np.linspace(-1.3, 2.5, 65)
arr2

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [4]:
n = 10
np.array([1, 2, 3] * n)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [5]:
number_even = 10
arr = np.arange(1, 2 * number_even, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [6]:
matrix = np.zeros((10,10))
matrix[0, :] = 1
matrix[9, :] = 1
matrix[:, 0] = 1
matrix[:, 9] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [7]:
matrix = np.zeros((8,8))
matrix[::2,::2] = 1
matrix[1::2,1::2] = 1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
n = 10
matrix = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        matrix[i][j] = i + j
matrix

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [9]:
vect1 = np.array([[1, 2, 3]])
vect2 = np.array([[1], [2], [3]])
matrix = np.array([[1, 2, 3], [2, 1, 4], [3, 9, 5]])
matrix2 = np.array([[1, 2], [1, 2], [4, 5]])
print(np.dot(vect1, vect2))
print(np.dot(matrix, vect2))
print(np.dot(matrix, matrix2))

[[14]]
[[14]
 [16]
 [36]]
[[15 21]
 [19 26]
 [32 49]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [10]:
cosinus = np.cos(np.linspace(0, 1, int(1/0.05)))
sinus = np.sin(np.linspace(0, 1, int(1/0.05)))

list(cosinus)+list(sinus)

[1.0,
 0.9986152781425827,
 0.9944649474795756,
 0.9875605021181478,
 0.9779210635311101,
 0.9655733276010717,
 0.9505514906876966,
 0.9328971549228098,
 0.912659212995635,
 0.8898937127472434,
 0.8646637019492132,
 0.8370390536963741,
 0.8070962728972044,
 0.7749182843977933,
 0.7405942033261461,
 0.7042190882928544,
 0.6658936781316236,
 0.625724112908743,
 0.5838216399741468,
 0.5403023058681398,
 0.0,
 0.05260728333807213,
 0.10506887376594912,
 0.15723948186175024,
 0.20897462406278547,
 0.2601310228046501,
 0.3105670033203749,
 0.3601428860007191,
 0.40872137322898616,
 0.4561679296190457,
 0.5023511546035127,
 0.547143146340223,
 0.5904198559291864,
 0.6320614309590333,
 0.6719525474315213,
 0.7099827291448582,
 0.7460466536513234,
 0.7800444439418607,
 0.8118819450498316,
 0.8414709848078965]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [11]:
matrix = np.random.rand(3,5)*4-1
matrix

array([[ 1.76355436,  0.79141911,  1.56914818,  0.5623592 ,  1.45526678],
       [-0.8841544 ,  1.63494645,  2.99563253,  2.68154944,  0.52410103],
       [ 0.98291864, -0.03966304,  0.49432942, -0.38848615,  0.05437325]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [12]:
print(matrix.sum())
print(matrix.sum(0)) # сумма по столбцам
print(matrix.sum(1)) # сумма по строкам
print(matrix.mean(1)) # среднее значение по строкам
print(matrix.var(1)) # дисперсия по строкам
print(matrix.std(1)) # ст. откл. по строкам

14.197294803449958
[1.8623186  2.38670253 5.05911013 2.85542249 2.03374106]
[6.14174762 6.95207506 1.10347213]
[1.22834952 1.39041501 0.22069443]
[0.21770614 2.04554259 0.22448231]
[0.4665899  1.43022466 0.47379565]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [13]:
for i in range(len(matrix)):
    matrix[i,:] -= matrix.mean(1)[i]
    matrix[i,:] /= matrix.std(1)[i]
matrix

array([[ 1.14705619, -0.9364335 ,  0.73040297, -1.42735692,  0.48633126],
       [-1.59035812,  0.17097415,  1.1223534 ,  0.90274938, -0.60571881],
       [ 1.60876154, -0.54951425,  0.57753801, -1.2857454 , -0.3510399 ]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [14]:
matrix[matrix[:, 2].argsort()]

array([[ 1.60876154, -0.54951425,  0.57753801, -1.2857454 , -0.3510399 ],
       [ 1.14705619, -0.9364335 ,  0.73040297, -1.42735692,  0.48633126],
       [-1.59035812,  0.17097415,  1.1223534 ,  0.90274938, -0.60571881]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [15]:
b = np.dot(np.transpose(matrix), matrix)
c = np.dot(matrix, np.transpose(matrix))
print(b)
print(c)

[[ 6.43309054 -2.23008937 -0.01800966 -5.14141115  0.95641964]
 [-2.23008937  1.20810578 -0.80944577  2.19750708 -0.36607772]
 [-0.01800966 -0.80944577  2.12671582 -0.77190874 -0.52735165]
 [-5.14141115  2.19750708 -0.77190874  4.50544547 -0.78963265]
 [ 0.95641964 -0.36607772 -0.52735165 -0.78963265  0.72664238]]
[[ 5.         -2.74769136  4.44625484]
 [-2.74769136  5.         -2.95233235]
 [ 4.44625484 -2.95233235  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [16]:
np.sum(np.diagonal(b)) + np.sum(np.diagonal(c))


29.999999999999996

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [17]:
#print(np.linalg.det(matrix)) A не квадратная, ошибка.
print(np.linalg.det(b))
print(np.linalg.det(c))
print(np.linalg.matrix_rank(matrix))
print(np.linalg.matrix_rank(b))
print(np.linalg.matrix_rank(c))
w_b, v_b = np.linalg.eig(b)
w_c, v_b = np.linalg.eig(c)
print(w_b)
print(w_c)

-1.16167068694275e-31
16.960629570151596
3
3
3
[ 1.18265883e+01  2.62763109e+00  5.45780605e-01 -7.67306024e-18
 -1.82484625e-16]
[11.8265883   0.5457806   2.62763109]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [18]:
np.random.seed(1032201722)
np.random.randint(9)

8

In [19]:
print('Аналитическое решение интеграла 8: ', 2-np.log(5))
print('Аналитическое решение интеграла 9: ', np.pi/(2**(3/2)))

Аналитическое решение интеграла 8:  0.3905620875658997
Аналитическое решение интеграла 9:  1.1107207345395915


In [22]:
def func1(x):
    return (2*x-1)/(2*x+1)

def func2(x):
    return 1/np.sqrt(2+3*x-2*x**2, where = x!=2)

def solution(func,a, b, dx, method):
    n = int((b-a) / dx)
    xx = np.linspace(a, b, n)
    if method == 'rectangular':
        return dx*np.sum(func(xx))
    elif method == 'trapezoid':
        return dx/2*(func(xx[0]) + 2*np.sum(func(xx[1:-1])) + func(xx[-1]))
    elif method == 'simpson':
        return dx/3*(func(xx[0]) + 2*np.sum(func(xx[2:-1:2])) + 4*np.sum(func(xx[1:-2:2])) + func(xx[-1]))
    else:
        return 'Неверный метод'
    
print('Для интеграла 8:', solution(func1, -2, -1, 0.0001, 'rectangular'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'rectangular') )
print('Для интеграла 8:', solution(func1, -2, -1, 0.0001, 'trapezoid'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'trapezoid') )
print('Для интеграла 8:', solution(func1, -2, -1, 0.0001, 'simpson'), 'Для интеграла 9:', solution(func2, 3/4, 2, 0.0001, 'simpson') ) 

Для интеграла 8: 2.0986357637358357 Для интеграла 9: 1.1041419998928388
Для интеграла 8: 2.098402430402502 Для интеграла 9: 1.1041172156215913
Для интеграла 8: 2.0983024341065764 Для интеграла 9: 1.1032101773676126
